// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package custom

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed fonts/PTSans-Bold.ttf
var ResourcePTSansBoldTtfData []byte
var ResourcePTSansBoldTtf = &fyne.StaticResource{
	StaticName:    "fonts/PTSans-Bold.ttf",
	StaticContent: ResourcePTSansBoldTtfData,
}
